services:
  backend:
    build:
      context: ./  # Путь к папке с исходниками бэкенда
      dockerfile: Dockerfile  # Указание на Dockerfile для бэкенда
    ports:
      - "8080:8080"  # Прокси порт для доступа к бэкенду
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/bloss_docker_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      - db  # Бэкенд будет запускаться после базы данных
    networks:
      - app-network

  db:
    image: postgres:latest
    environment:
      - POSTGRES_DB=bloss_docker_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_MAX_CONNECTIONS=300
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  minio:
    image: minio/minio:latest
    environment:
      - MINIO_ACCESS_KEY=admin
      - MINIO_SECRET_KEY=12345678
    ports:
      - "9000:9000"
      - "9090:9090"
    volumes:
      - minio_data:/minio
    command: server ~/minio --console-address :9090
    networks:
      - app-network

volumes:
  postgres_data:
    driver: local
  minio_data:
    driver: local

networks:
  app-network:
    driver: bridge